"""Streamlit regression for year comparisons and explicit chart requests."""
from test_agent import ScriptedModel, provider_failure
# Importing these fixtures registers them with pytest in this module.
from test_ui import button, connected_ui, isolated_ui_cache
from test_year_comparison_flow import QUESTION, YEAR_ROWS, make_year_result, wrong_all_time_proposal


def setup_year_question(monkeypatch, connected_ui):
    import olist_agent.agent.model as model_module

    app, query, store = connected_ui
    model = ScriptedModel(scripts=[wrong_all_time_proposal(), provider_failure])
    monkeypatch.setattr(model_module, "load_model", lambda factory: model)
    def execute(spec, session):
        query.calls.append(spec)
        return make_year_result(store, session, spec)
    monkeypatch.setattr(query, "execute", execute)
    return app, query, store, model


def test_explicit_graph_question_enables_charts_and_plots_after_sql_approval(connected_ui, monkeypatch):
    app, query, store, model = setup_year_question(monkeypatch, connected_ui)
    assert not app.sidebar.toggle[0].value
    assert not app.get("plotly_chart")
    app.chat_input[0].set_value(QUESTION).run(timeout=20)
    assert not app.exception
    assert app.sidebar.toggle[0].value and app.sidebar.toggle[0].disabled
    assert not query.calls and not store.results and not store.reports
    assert not app.dataframe and not app.get("plotly_chart")
    assert "IN (2016, 2018)" in app.code[0].value
    assert "ORDER BY year" in app.code[0].value
    assert "customer_state IN" not in app.code[0].value
    assert any("SQL generated by Gemini" in item.value for item in app.caption)
    assert button(app, "Approve and run")

    button(app, "Approve and run").click().run(timeout=20)
    assert not app.exception
    assert len(query.calls) == 1 and model.position == 1
    assert len(app.dataframe) == 1 and len(app.get("plotly_chart")) == 1
    frame = app.dataframe[0].value
    assert frame[["year", "value"]].to_dict("records") == [
        {"year": row["year"], "value": row["value"]} for row in YEAR_ROWS]
    assert any("54,011" in item.value for item in app.markdown)
    assert button(app, QUESTION[:65])
    assert not app.chat_input[0].disabled
    assert not any(item.label == "Approve and run" for item in app.button)


def test_explicit_chart_request_can_be_rejected_without_query_table_or_graph(connected_ui, monkeypatch):
    app, query, store, model = setup_year_question(monkeypatch, connected_ui)
    app.chat_input[0].set_value(QUESTION).run(timeout=20)
    assert app.sidebar.toggle[0].value
    button(app, "Reject").click().run(timeout=20)
    assert not app.exception
    assert not query.calls and not store.results
    assert not app.dataframe and not app.get("plotly_chart")
    assert model.position == 1
    assert button(app, QUESTION[:65])
    assert not app.chat_input[0].disabled
